name: Full Build

permissions:
  contents: write

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag number from tag string
        id: tag_number
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          orig_tag="${{ github.ref_name }}"
          echo "tag_number=${orig_tag/v/}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          path: master

      - name: Checkout MonoBehaviour
        uses: actions/checkout@v4
        with:
          ref: MonoBehaviour
          path: MonoBehaviour

      - name: Setup MAPI
        uses: BadMagic100/setup-hk@v2
        with:
          apiPath: HkRefs
          dependencyFilePath: master/ModDependencies.txt

      # should be part of the installed software of the runner
      #- name: Setup .NET
      #  uses: actions/setup-dotnet@v4
      #  with:
      #    dotnet-version: 9
      #    cache: true

      - name: Install dependencies MonoBehaviour
        run: dotnet restore
        shell: bash
        working-directory: MonoBehaviour

      - name: Build MonoBehaviour
        run: dotnet build -c Release
        shell: bash
        working-directory: MonoBehaviour

      - name: Prepare MonoBehaviour artifacts for release
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: Publish-MonoBehaviour
          path: MonoBehaviour/bin/Publish

      - name: Install dependencies master
        run: dotnet restore
        shell: bash
        working-directory: master

      - name: Build master
        run: dotnet build -c Release /p:AssemblyVersion=${{ steps.tag_number.outputs.tag_number }}
        shell: bash
        working-directory: master

      - name: Prepare master artifacts for release
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: Publish-Master
          path: master/bin/Publish

  release:
    if: ${{ startsWith( github.ref, 'refs/tags/' ) }}
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: christopherhx/gitea-download-artifact@v4
        with:
          path: artifacts

      - name: Get build details
        id: details
        # this assumes that an MSBuild task that writes the SHA256 of the zip file to SHA.txt, and the mod version (usually
        # the same as the assembly version) to version.txt. The contents of these files are read to step outputs for use in release
        run: |
          sha="$(sed '4q;d' artifacts/Publish-Master/SFCore/SHA.txt)"
          ver="${{ github.ref_name }}"
          echo "archiveHash=$sha" >> $GITHUB_OUTPUT
          echo "buildVersion=$ver" >> $GITHUB_OUTPUT
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          tag_name: ${{ steps.details.outputs.buildVersion }}
          body: |
            SHA256 of SFCore.zip: ${{ steps.details.outputs.archiveHash }}  
            Attachments:  
            - SFCore.zip
              - to be used for the ModInstaller
            - SFCore.dll
              - the mod, also inside SFCore.zip
            - SFCoreUnity.dll
              - the mod, to be used in a Unity project for the use of its MonoBehaviours
          files: |
            artifacts/Publish-Master/SFCore/SFCore.zip
            artifacts/Publish-Master/SFCore/SFCore.dll
            artifacts/Publish-MonoBehaviour/SFCore/SFCoreUnity.dll
